[tool.mypy]
  plugins = [
    "pydantic.mypy",
  ]

  check_untyped_defs    = true
  disallow_any_generics = true
  no_implicit_reexport  = true
  warn_redundant_casts  = true
  warn_unused_ignores   = true

  # for strict mypy: (this is the tricky one :-))
  disallow_untyped_defs = true

[tool.pydantic-mypy]
  init_forbid_extra             = true
  init_typed                    = true
  warn_required_dynamic_aliases = true
  warn_untyped_fields           = true
